spring.application.name=climalert

# WeatherAPI Configuration
weather.api.key=API-KEY-EXAMPLE
weather.api.base-url=http://api.weatherapi.com/v1
weather.api.ubicacion=CABA

# Email Configuration
email.alertas.remitente=alertas@clima.com
email.alertas.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# SMTP Configuration (Spring Mail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=CAMBIAR_USUARIO
spring.mail.password=CAMBIAR_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
